/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedWhitelistRouteImport } from './routes/_authenticated/whitelist'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedBeatsRouteImport } from './routes/_authenticated/beats'
import { Route as AuthenticatedAgreementsRouteImport } from './routes/_authenticated/agreements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as BSlugOfferRouteImport } from './routes/b.$slug.offer'
import { Route as AuthenticatedAdminWhitelistRouteImport } from './routes/_authenticated/admin/whitelist'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminOnlineRouteImport } from './routes/_authenticated/admin/online'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminGiftRouteImport } from './routes/_authenticated/admin/gift'
import { Route as AuthenticatedAdminFunnelsRouteImport } from './routes/_authenticated/admin/funnels'
import { Route as AuthenticatedAdminBeatsRouteImport } from './routes/_authenticated/admin/beats'
import { Route as AuthenticatedAdminAgreementsRouteImport } from './routes/_authenticated/admin/agreements'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminFunnelsIdRouteImport } from './routes/_authenticated/admin/funnels.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhitelistRoute = AuthenticatedWhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBeatsRoute = AuthenticatedBeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgreementsRoute = AuthenticatedAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BSlugOfferRoute = BSlugOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => BSlugRoute,
} as any)
const AuthenticatedAdminWhitelistRoute =
  AuthenticatedAdminWhitelistRouteImport.update({
    id: '/whitelist',
    path: '/whitelist',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOnlineRoute =
  AuthenticatedAdminOnlineRouteImport.update({
    id: '/online',
    path: '/online',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiftRoute = AuthenticatedAdminGiftRouteImport.update({
  id: '/gift',
  path: '/gift',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFunnelsRoute =
  AuthenticatedAdminFunnelsRouteImport.update({
    id: '/funnels',
    path: '/funnels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBeatsRoute = AuthenticatedAdminBeatsRouteImport.update({
  id: '/beats',
  path: '/beats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAgreementsRoute =
  AuthenticatedAdminAgreementsRouteImport.update({
    id: '/agreements',
    path: '/agreements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminFunnelsIdRoute =
  AuthenticatedAdminFunnelsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminFunnelsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/beats': typeof AuthenticatedBeatsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/whitelist': typeof AuthenticatedWhitelistRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/admin/beats': typeof AuthenticatedAdminBeatsRoute
  '/admin/funnels': typeof AuthenticatedAdminFunnelsRouteWithChildren
  '/admin/gift': typeof AuthenticatedAdminGiftRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/online': typeof AuthenticatedAdminOnlineRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/b/$slug/offer': typeof BSlugOfferRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/funnels/$id': typeof AuthenticatedAdminFunnelsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/beats': typeof AuthenticatedBeatsRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/whitelist': typeof AuthenticatedWhitelistRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/admin/beats': typeof AuthenticatedAdminBeatsRoute
  '/admin/funnels': typeof AuthenticatedAdminFunnelsRouteWithChildren
  '/admin/gift': typeof AuthenticatedAdminGiftRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/online': typeof AuthenticatedAdminOnlineRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/b/$slug/offer': typeof BSlugOfferRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/funnels/$id': typeof AuthenticatedAdminFunnelsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agreements': typeof AuthenticatedAgreementsRoute
  '/_authenticated/beats': typeof AuthenticatedBeatsRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/whitelist': typeof AuthenticatedWhitelistRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/_authenticated/admin/agreements': typeof AuthenticatedAdminAgreementsRoute
  '/_authenticated/admin/beats': typeof AuthenticatedAdminBeatsRoute
  '/_authenticated/admin/funnels': typeof AuthenticatedAdminFunnelsRouteWithChildren
  '/_authenticated/admin/gift': typeof AuthenticatedAdminGiftRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/online': typeof AuthenticatedAdminOnlineRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/whitelist': typeof AuthenticatedAdminWhitelistRoute
  '/b/$slug/offer': typeof BSlugOfferRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/funnels/$id': typeof AuthenticatedAdminFunnelsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/account'
    | '/admin'
    | '/agreements'
    | '/beats'
    | '/downloads'
    | '/whitelist'
    | '/b/$slug'
    | '/checkout/return'
    | '/claim/$token'
    | '/admin/agreements'
    | '/admin/beats'
    | '/admin/funnels'
    | '/admin/gift'
    | '/admin/import'
    | '/admin/online'
    | '/admin/support'
    | '/admin/whitelist'
    | '/b/$slug/offer'
    | '/admin/'
    | '/admin/funnels/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/account'
    | '/agreements'
    | '/beats'
    | '/downloads'
    | '/whitelist'
    | '/b/$slug'
    | '/checkout/return'
    | '/claim/$token'
    | '/admin/agreements'
    | '/admin/beats'
    | '/admin/funnels'
    | '/admin/gift'
    | '/admin/import'
    | '/admin/online'
    | '/admin/support'
    | '/admin/whitelist'
    | '/b/$slug/offer'
    | '/admin'
    | '/admin/funnels/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/agreements'
    | '/_authenticated/beats'
    | '/_authenticated/downloads'
    | '/_authenticated/whitelist'
    | '/b/$slug'
    | '/checkout/return'
    | '/claim/$token'
    | '/_authenticated/admin/agreements'
    | '/_authenticated/admin/beats'
    | '/_authenticated/admin/funnels'
    | '/_authenticated/admin/gift'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/online'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/whitelist'
    | '/b/$slug/offer'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/funnels/$id'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BSlugRoute: typeof BSlugRouteWithChildren
  ClaimTokenRoute: typeof ClaimTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whitelist': {
      id: '/_authenticated/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof AuthenticatedWhitelistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/beats': {
      id: '/_authenticated/beats'
      path: '/beats'
      fullPath: '/beats'
      preLoaderRoute: typeof AuthenticatedBeatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agreements': {
      id: '/_authenticated/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AuthenticatedAgreementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/b/$slug/offer': {
      id: '/b/$slug/offer'
      path: '/offer'
      fullPath: '/b/$slug/offer'
      preLoaderRoute: typeof BSlugOfferRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/_authenticated/admin/whitelist': {
      id: '/_authenticated/admin/whitelist'
      path: '/whitelist'
      fullPath: '/admin/whitelist'
      preLoaderRoute: typeof AuthenticatedAdminWhitelistRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/online': {
      id: '/_authenticated/admin/online'
      path: '/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AuthenticatedAdminOnlineRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gift': {
      id: '/_authenticated/admin/gift'
      path: '/gift'
      fullPath: '/admin/gift'
      preLoaderRoute: typeof AuthenticatedAdminGiftRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funnels': {
      id: '/_authenticated/admin/funnels'
      path: '/funnels'
      fullPath: '/admin/funnels'
      preLoaderRoute: typeof AuthenticatedAdminFunnelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/beats': {
      id: '/_authenticated/admin/beats'
      path: '/beats'
      fullPath: '/admin/beats'
      preLoaderRoute: typeof AuthenticatedAdminBeatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/agreements': {
      id: '/_authenticated/admin/agreements'
      path: '/agreements'
      fullPath: '/admin/agreements'
      preLoaderRoute: typeof AuthenticatedAdminAgreementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/funnels/$id': {
      id: '/_authenticated/admin/funnels/$id'
      path: '/$id'
      fullPath: '/admin/funnels/$id'
      preLoaderRoute: typeof AuthenticatedAdminFunnelsIdRouteImport
      parentRoute: typeof AuthenticatedAdminFunnelsRoute
    }
  }
}

interface AuthenticatedAdminFunnelsRouteChildren {
  AuthenticatedAdminFunnelsIdRoute: typeof AuthenticatedAdminFunnelsIdRoute
}

const AuthenticatedAdminFunnelsRouteChildren: AuthenticatedAdminFunnelsRouteChildren =
  {
    AuthenticatedAdminFunnelsIdRoute: AuthenticatedAdminFunnelsIdRoute,
  }

const AuthenticatedAdminFunnelsRouteWithChildren =
  AuthenticatedAdminFunnelsRoute._addFileChildren(
    AuthenticatedAdminFunnelsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAgreementsRoute: typeof AuthenticatedAdminAgreementsRoute
  AuthenticatedAdminBeatsRoute: typeof AuthenticatedAdminBeatsRoute
  AuthenticatedAdminFunnelsRoute: typeof AuthenticatedAdminFunnelsRouteWithChildren
  AuthenticatedAdminGiftRoute: typeof AuthenticatedAdminGiftRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminOnlineRoute: typeof AuthenticatedAdminOnlineRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminWhitelistRoute: typeof AuthenticatedAdminWhitelistRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAgreementsRoute: AuthenticatedAdminAgreementsRoute,
  AuthenticatedAdminBeatsRoute: AuthenticatedAdminBeatsRoute,
  AuthenticatedAdminFunnelsRoute: AuthenticatedAdminFunnelsRouteWithChildren,
  AuthenticatedAdminGiftRoute: AuthenticatedAdminGiftRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminOnlineRoute: AuthenticatedAdminOnlineRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminWhitelistRoute: AuthenticatedAdminWhitelistRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgreementsRoute: typeof AuthenticatedAgreementsRoute
  AuthenticatedBeatsRoute: typeof AuthenticatedBeatsRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedWhitelistRoute: typeof AuthenticatedWhitelistRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgreementsRoute: AuthenticatedAgreementsRoute,
  AuthenticatedBeatsRoute: AuthenticatedBeatsRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedWhitelistRoute: AuthenticatedWhitelistRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface BSlugRouteChildren {
  BSlugOfferRoute: typeof BSlugOfferRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugOfferRoute: BSlugOfferRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BSlugRoute: BSlugRouteWithChildren,
  ClaimTokenRoute: ClaimTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
